version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "50051:50051"  # Assuming gRPC port
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=localhost:8443
      - DB_USER=postgres
      - DB_PASSWORD=12345
      - DB_NAME=speech_temp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=speech_temp
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U youruser"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: