// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"database/sql"
	"speech/config"
	"speech/internal/auth"
)

// Injectors from wire.go:

func InitializeAuthHandler(cfg *config.Config, db *sql.DB) (*auth.AuthHandler, error) {
	repository := auth.NewPostgresRepository(db)
	smtpConfig := provideSMTPConfig(cfg)
	service := auth.NewAuthService(repository, cfg, smtpConfig)
	authHandler := auth.NewAuthHandler(service)
	return authHandler, nil
}

// wire.go:

func provideSMTPConfig(cfg *config.Config) auth.SMTPConfig {
	return auth.SMTPConfig{
		Host:     cfg.SMTPHost,
		Port:     cfg.SMTPPort,
		Username: cfg.SMTPUsername,
		Password: cfg.SMTPPassword,
	}
}
